'use strict';
const $=id=>document.getElementById(id), catalogue=window.CA_CATALOGUE;
const palettes={};$('palette').replaceChildren(new Option('Recorded','original'));window.CA_PALETTES.forEach((p,i)=>{const key='palette-'+i;palettes[key]=Object.fromEntries([...'WRGBK'].map(s=>[s,p[s]+'ff']));$('palette').add(new Option(p.name,key));});
let selected, displayed, displayedRows, revision=0;
function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
async function hash(x){const data=new TextEncoder().encode(canonical(x));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',data))].map(b=>b.toString(16).padStart(2,'0')).join('');}
function evolve(d,count){return CAWorld.run(d,count).rows;}
function render(rows,w){const cv=$('canvas'),ctx=cv.getContext('2d'),sx=10,sy=17;cv.width=(w.dynamics.width+1)*sx;cv.height=rows.length*sy;ctx.fillStyle=w.appearance.canvasBackground;ctx.fillRect(0,0,cv.width,cv.height);const edges=new Map();
 rows.forEach((row,r)=>[...row].forEach((s,c)=>{if(s==='W')return;let p=(r+c+w.geometry.phase)%2?[[c,r],[c+1,r+1],[c+2,r]]:[[c,r+1],[c+1,r],[c+2,r+1]];ctx.beginPath();p.forEach(([x,y],i)=>i?ctx.lineTo(x*sx,y*sy):ctx.moveTo(x*sx,y*sy));ctx.closePath();ctx.fillStyle=w.appearance.palette[s];ctx.fill();for(let i=0;i<3;i++){let a=p[i],b=p[(i+1)%3],key=[a.join(','),b.join(',')].sort().join('|');if(!edges.has(key))edges.set(key,{a,b,states:[]});edges.get(key).states.push(s);}}));
 ctx.strokeStyle=w.appearance.borderColor;ctx.lineWidth=w.appearance.borderWidth;ctx.beginPath();for(const {a,b,states}of edges.values()){if(states.length===1||new Set(states).size>1){ctx.moveTo(a[0]*sx,a[1]*sy);ctx.lineTo(b[0]*sx,b[1]*sy);}}ctx.stroke();}
function entryList(){let q=$('search').value.toLowerCase();$('entries').replaceChildren();const groups=new Map();for(const e of catalogue.entries){if(!`${e.name} ${e.world.dynamics.seed} ${e.world.dynamics.width} ${e.ruleCount}`.toLowerCase().includes(q))continue;const family=e.ruleFamilyId;let group=groups.get(family);if(!group){group=document.createElement('div');const heading=document.createElement('small');heading.textContent=`${e.ruleCount} rules`;heading.title=family;group.append(heading);groups.set(family,group);$('entries').append(group);}const b=document.createElement('button');b.style.width='100%';b.style.marginTop='6px';b.textContent=e.name;const s=document.createElement('small');s.textContent=`${e.world.dynamics.width} cells`;b.append(s);b.classList.toggle('active',selected?.key===e.key);b.onclick=()=>choose(e);group.append(b);}}

function choose(e){selected=e;$('name').textContent=e.name;$('openExplorer').href='../impossible-fractal-ca.html?world='+e.key;$('rows').value=e.world.observation.rowCount;$('phase').value=e.world.geometry.phase;$('palette').value='original';$('download').href=e.download;entryList();replay();}
async function replay(){let token=++revision;displayed=null;try{const count=Number($('rows').value);if(!Number.isInteger(count)||count<1||count>512)throw Error('Choose 1–512 rows.');let w=structuredClone(selected.world);w.geometry.phase=Number($('phase').value);const pal=$('palette').value;if(pal!=='original'){w.appearance.palette=structuredClone(palettes[pal]);w.appearance.canvasBackground=palettes[pal].W;}
 const rows=evolve(w.dynamics,count),k=rows.reduce((n,r)=>n+[...r].filter(s=>s==='K').length,0);render(rows,w);
 const d=await hash(w.dynamics);w.geometry.dynamicsId=d;const g=await hash(w.geometry);w.appearance.geometryId=g;const a=await hash(w.appearance);w.ids={dynamics:d,geometry:g,appearance:a};w.observation={schema:'ca-observation-v1',appearanceId:a,firstGeneration:0,rowCount:count,renderer:'catalogue-canvas-v1',crop:'full-domain',gridSha256:await hash(rows)};w.ids.observation=await hash(w.observation);if(token!==revision)return;
 displayed=w;displayedRows=rows;const same=count===selected.world.observation.rowCount;const verified=same&&w.observation.gridSha256===selected.world.observation.gridSha256;
 $('facts').textContent=`${w.dynamics.rules.length} rules · ${w.dynamics.width} cells wide · ${w.dynamics.boundary} boundaries · ${count} rows including the seed`;
 $('notice').textContent=[k?`${k} undefined cells.`:'',same&&!verified?'Replay checksum mismatch.':''].filter(Boolean).join(' ');
 }catch(e){$('notice').textContent=e.message;displayed=null;}}
$('export').onclick=()=>{if(!displayed)return;const w=structuredClone(displayed);w.metadata={name:selected.name+' / displayed configuration',derivedFrom:selected.world.ids.appearance,note:'Original evidence applies only to the recorded configuration and horizon.',sourceEvidence:selected.world.metadata.evidence};const blob=new Blob([JSON.stringify(w,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=w.ids.appearance+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('search').oninput=entryList;$('replay').onclick=replay;choose(catalogue.entries.find(e=>e.key==='entry-019')||catalogue.entries[0]);
